Repository bob-fornal/edje-buzzer-react, pull requests merged in 2022-08, with the labels that each got.

#1 BASE React Project
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Pages/Display/Display.js
  src/Pages/Management/Management.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: PROJECT

#5 Diagnostic and Buzzer Pages Added!
  package-lock.json
  package.json
  src/App.jsx
  src/Pages/Buzzer/index.jsx
  src/Pages/Diagnostic/index.jsx
Labels: BUZZER, PROJECT

#6 ISSUE-4 Add Material UI
  config-overrides.js
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/Core/Constants/config.json
  src/Features/Links/Links.css
  src/Features/Links/index.jsx
  src/Features/Version/index.jsx
  src/Pages/Buzzer/index.jsx
  src/Pages/Diagnostic/index.jsx
  src/Pages/Display/index.jsx
  src/Pages/Management/Management.css
  src/Pages/Management/index.jsx
  src/Shared/Title/index.jsx
  src/index.css
Labels: FEATURE
